#file: noinspection SpellCheckingInspection
server:
  port: 8080
spring:
  application:
    name: partTimeJob
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/graduation_project
      username: root
      password: 123456
  redis:
    host: 192.168.200.146
    port: 6379
    password: 123456
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  mail:
    host: smtp.qq.com             # 此处使用的是qq邮箱进行邮件发送
    username: 2084933310@qq.com   # 发送邮件的账号（也就是本人账号）
    password: gwqnychthjmyfcdd    # 账号秘钥（注意这不是登录你QQ邮箱的密码！该秘钥在开启SMTP服务时会给出。）
    default-encoding: UTF-8       #编码风格
    port: 587                     #占用端口
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: 192.168.200.146 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: root
    password: 123456
    virtual-host: /
    publisher-confirm-type: correlated #开启confirmCallBack
    publisher-returns: true #开启returnCallBack
    template:
      mandatory: true
    listener:
       simple:
         acknowledge-mode: auto #消费者确认机制
         prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
         retry:
           enabled: true # 开启消费者失败重试
           initial-interval: 1000 # 初识的失败等待时长为1秒
           multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
           max-attempts: 3 # 最大重试次数
           stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
minio:
  accessKey: minio123456
  secretKey: minio123456
  bucket: parttimejob
  endpoint: http://192.168.200.146:9000
  readPath: http://192.168.200.146:9000
jwt:
  property:
    user-secret-key: PartTimeJob
    user-ttl: 63000000
    user-token-name: Authorization
logging:
  level:
    root: info
